### ISSUE TITLE
Error: sftp.connect: Handshake failed: no matching client->server cipher after 2 attempts

### ISSUE THREAD

**Issue by serdar** [theophilusx/ssh2-sftp-client#186]
I'm trying to connect to an SFTP server using a private key but getting a handshake error due to a mismatch between ciphers.
The server is using the same cipher as is in my key (aes256-cbc):
```
>sftp serverhost
Unable to negotiate with xxx.xxx.xxx.xx port 22: no matching cipher found. 
Their offer: aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,blowfish-cbc
```
My private key file also has the same cipher:
```
PuTTY-User-Key-File-2: ssh-rsa
Encryption: aes256-cbc
Comment: rsa-key-20191022
```

I have 4.2.2 of the package installed, and my code from the examples:

```
let Client = require("ssh2-sftp-client");
  let sftp = new Client();

  sftp
    .connect({
      host: "serverhost",
      port: "22",
      username: "user_name",
      passphrase: 'passphrase',
      privateKey: fs.readFileSync('./my.ppk'),
      readyTimeout: 2000
    })
    .then(() => {
      return sftp.list("/");
    })
    .then(data => {
      console.log(data, "the data info");
    })
    .catch(err => {
      console.log(err, "catch error");
    });
```

And the error:
```
Error: sftp.connect: Handshake failed: no matching client->server cipher after 2 attempts
    at formatError (/Users/skilic/dev/graph-auth/node_modules/ssh2-sftp-client/src/index.js:60:10)
    at Client.self.client.on.on.err (/Users/skilic/dev/graph-auth/node_modules/ssh2-sftp-client/src/index.js:861:22)
    at Client.emit (events.js:189:13)
    at SSH2Stream.<anonymous> (/Users/skilic/dev/graph-auth/node_modules/ssh2/lib/client.js:359:10)
    at SSH2Stream.emit (events.js:194:15)
    at check_KEXINIT (/Users/skilic/dev/graph-auth/node_modules/ssh2-streams/lib/ssh.js:2397:10)
    at check (/Users/skilic/dev/graph-auth/node_modules/ssh2-streams/lib/ssh.js:2274:9)
    at onKEXINIT (/Users/skilic/dev/graph-auth/node_modules/ssh2-streams/lib/ssh.js:2271:5)
    at SSH2Stream.<anonymous> (/Users/skilic/dev/graph-auth/node_modules/ssh2-streams/lib/ssh.js:208:5)
    at SSH2Stream.emit (events.js:189:13) 'catch error'
```

**Comment by theophilusx** [comment]
That looks like it could be that the underlying ssh2 module which handles all the ssh/sftp interactions does not support aes256-cbc. First thing you need to do is check the ssh2 package documentation to verify it supports that cipher. If it doesn't, you will either need to select a different cipher or report a bug to ssh2.

**Comment by serdar** [comment]
Thanks @theophilusx - so it does support it but it's an optional setting, so I added the following to the connect config:
```
algorithms: {
  cipher: [
    "aes256-cbc"
  ]
}
```

**Comment by waldyrious** [comment]
Thanks @serdar for [sharing the solution](https://xkcd.com/979/). I was facing the same issue :)

**Comment by larryq** [comment]
Same as @waldyrious, this thread helped me with my own sftp issue.
