### ISSUE TITLE
get and fastGet broken since >= 4.3.1 for Windows 2019 OpenSSH server

### ISSUE THREAD

**Issue by rajasdevel** [theophilusx/ssh2-sftp-client#216]
Following is the code to fetch a file from OpenSSH server installed on Windows Server 2019. I'm able to download the file on version <= `4.3.0`, SCP and SFTP clients. But both get and fastGet are broken since `4.3.1`.

```
let ClientSFTP = require( 'ssh2-sftp-client' );
let sftp = new ClientSFTP();
let remotePath, inputFile = 'test.csv';

sftp
.connect({
  host: process.env.SFTP_HOST,
  port: process.env.SFTP_PORT,
  username: process.env.SFTP_USERNAME,
  password: process.env.SFTP_PASSWORD,
})
.then(() => {
  return sftp.cwd();
})
.then(async (cwd) => {
  remotePath = `${ cwd }/${ inputFile }`;
  console.debug('Getting file: ', remotePath); // Path is correct, if I try to download this file with SCP or SFTP it works
  try {
  await sftp.get(remotePath, inputFile);
  } catch(e) {
  	console.error('Exception thrown: ', e);
  }
})
.finally(() => {
	sftp.end();
})

sftp.on( 'error', ( err ) => {
    console.error('Error caugth: ', err );
});
```

Works fine on `4.3.0`

On `4.3.1` throws following exceptions/errors:
```
Getting file:  /C:/Users/user_name/test.csv
events.js:293
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (sftp_test/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:316:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: '

```

On version `5.0.2` and `5.1.0`, the code throws following exception/error:

```
Getting file:  /C:/Users/user_name/test.csv
Exception thrown:  Error: get->get: No such file: 
    at Object.formatError (sftp_test/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at SftpClient.get (sftp_test/node_modules/ssh2-sftp-client/src/index.js:522:19)
    at sftp_test/index.js:21:3 {
  code: 'ENOENT',
  custom: true
}
Error caugth:  Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

**Comment by theophilusx** [comment]
It is quite likely there are bugs when it comes to downloading from a Windows based server as this is not a platform I use and so has lest testing. Having said that, I know that others are using it without problem. 

In this case, I think we first need to get rid of that await call you have in the middle of the promise chain. It isn't necessary and is just making things more complicated and difficult to debug. What I suspect may be happening is due to how the code is structured, the finally block may be getting called before your call to get() has been run. The error you are seeing is ECONRESET, which means that the remote server has cloesd the connection, which further supports this hypothesis. Try running the following and see if that works

````
let ClientSFTP = require('ssh2-sftp-client');
let sftp = new ClientSFTP();
let targetFile = 'test.csv';

sftp
  .connect({
    host: process.env.SFTP_HOST,
    port: process.env.SFTP_PORT,
    username: process.env.SFTP_USERNAME,
    password: process.env.SFTP_PASSWORD
  })
  .then(() => {
    return sftp.cwd();
  })
  .then(remoteDir => {
    let remotePath = `${remoteDir}/${targetFile}`;
    console.debug('Getting file: ', remotePath); // Path is correct, if I try to download this file with SCP or SFTP it works
    return sftp.get(remotePath, `./${targetFile}`);
  })
  .catch(e => {
    console.log(`Error: ${e.message}`);
  })
  .finally(() => {
    sftp.end();
  });
````

**Comment by rajasdevel** [comment]
@theophilusx You are right. That code indeed works with 5.1.0, and that resolves this issue for me, thank you.
