### ISSUE TITLE
put command fails with: Bad path: /<path>/some_file.txt must be a regular file 

### ISSUE THREAD

**Issue by coded-monkey** [theophilusx/ssh2-sftp-client#221]
Hi, 

As stated in the title, I get an error when I try to upload a file to a remote path. I'm guessing the configuration of the remote server is part of the issue because when connecting to other remote servers, I am able to upload files successfully. Unfortunately, I do not know much about the remote server that is failing aside from the credentials I used to connect, and the path I want to upload to.

Here is a snippet of my code:

    async uploadFiles() {
        const configFile = this.dependencies.configFile[this.currentActionIndex];
        const log = this.dependencies.log;

        const localFiles = configFile.local.files;
        const dst = configFile.remote.upload;

        for (let i = 0; i < localFiles.length; i++) {
            let localFile = localFiles[i];
            await sftp.put(localFile, `${dst}/${this.extractLocalFileName(localFile)}`);
            this.archiveFile(localFile);
            log.info(`Successfully uploaded ${localFile}`);
        }
    }

The path or in the case of my code, the dst variable is '/INBOX/../INBOX'

Node Version: 12.6.1
ssh2-sftp-client version: 5.0.2
My platform: Windows 10

Any help or information would be greatly appreciated!

Thanks!

**Comment by theophilusx** [comment]
The first thing you should try is upgrading to ssh2-sftp-client v 5.1.2.
It probably won't fix the problem, but might give more informative
diagnostics. 

I would also try manually uploading a file using something like openssh
sftp command, making sure to use the exact same path and login
credentials - you might get more informative errors or additional clues.

You could also try calling stat(), exists() and cwd() to verify the
remote server, current working directory and expected directories exist
etc. 

That dst path also looks a bit problematic. /INBOX/../INBOX - that path
is going to be the same as /INBOX

**Comment by coded-monkey** [comment]
Hi,

Thanks for the reply. 

I will try to update to the latest version of ssh2-sftp-client and try to call the APIs you have suggested. 

Regarding your suggestion to manually upload a file, I have done this previously (sorry for not mentioning it in my original post. I used WinSCP to manually transfer a file. I also tried a batch file that calls WinSCP commands as well. I am able to transfer the files successfully in both cases.

I will reply back once I have tried your other suggestions.

**Comment by coded-monkey** [comment]
I tired the exists, stat, and cwd api calls using ssh2-sftp-client v 5.1.2.

Here is a snippet of my log with the output of these apis:

```
2020-03-30 11:52:19.755 INFO  --------------------------------------------------------------------------- 
2020-03-30 11:52:19.756 INFO  Starting Action 1: upload 
2020-03-30 11:52:19.756 INFO  --------------------------------------------------------------------------- 
2020-03-30 11:52:19.756 INFO  Connecting...  
2020-03-30 11:52:22.253 INFO  Connected 
2020-03-30 11:52:22.456 INFO  exists: "d" 
2020-03-30 11:52:22.658 INFO  stat: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 11:52:22.856 INFO  cwd: "/" 
2020-03-30 11:52:23.061 ERROR put->put: Bad path: /INBOX/FTP.txt must be a regular file
{"code":"ERR_BAD_PATH","custom":true}
Error: put->put: Bad path: /INBOX/FTP.txt must be a regular file
    at Object.formatError (D:\Documents\Work\Git_Repo\A\repo\NodeJS\FTPClient\node_modules\ssh2-sftp-client\src\utils.js:62:18)
    at SftpClient.put (D:\Documents\Work\Git_Repo\A\repo\NodeJS\FTPClient\node_modules\ssh2-sftp-client\src\index.js:740:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UseCases.uploadFiles (D:\Documents\Work\Git_Repo\A\repo\NodeJS\FTPClient\src\use_case\UseCases.js:263:13)
    at async checkIfUploadFilesOrFolder (D:\Documents\Work\Git_Repo\A\repo\NodeJS\FTPClient\src\main\ftpclient.js:123:24)
    at async main (D:\Documents\Work\Git_Repo\A\repo\NodeJS\FTPClient\src\main\ftpclient.js:47:21) 
2020-03-30 11:52:23.061 ERROR Error occured during upload/download... Disconnect from the FTP server 
2020-03-30 11:52:23.061 INFO  Completed Action 1. 
2020-03-30 11:52:23.062 INFO  Disconnected from server
```

**Comment by theophilusx** [comment]
What is the output from

stat('/INBOX');

and

stat('/INBOX/FTP.txt');

My guess is that either
 1. /INBOX does not exist
 2. /INBOX does not have write permission
 3. /INBOX/FTP.txt exists and you don't have write permission
 4. /INBOX/FTP.txt exists and is not a regular file (so cannot be over written)

If I can reproduce the same file hierarchy and permissions, i can debug
from here to see what might be the issue.

**Comment by coded-monkey** [comment]
The exits and stat api calls for the log snippet above are for /INBOX (sorry I did not mention this). 

Here is the comparison for you requested (I added exists call as well):
```
2020-03-30 13:55:26.424 INFO  exists for /INBOX: "d" 
2020-03-30 13:55:26.621 INFO  exists for /INBOX/FTP_debug.txt: "d" 
2020-03-30 13:55:26.816 INFO  stat for /INBOX: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 13:55:27.014 INFO  stat for /INBOX/FTP_debug.txt: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 13:55:27.208 INFO  cwd: "/"


```

**Comment by theophilusx** [comment]
> 2020-03-30 13:55:26.424 INFO  exists for /INBOX: "d" 
> 2020-03-30 13:55:26.621 INFO  exists for /INBOX/FTP_debug.txt: "d" 
> 2020-03-30 13:55:26.816 INFO  stat for /INBOX: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 

From the above /INBOX/FTP_debug.txt is a DIRECTORY, so you cannot 'put'
a file to it. As documented in the README, the path must include the
remote filename where the file is to be put. This must either be an
existing file name (in which case it will be overwritten) or a new
non-existent file, in which case it will be created. However, if it
already exists as a non-file i.e. directory, then put will fail with the
bad path error.

BTW you are better off using fastPut if you are just uploading files.
Put is useful when you want to upload the contents of a stream or
buffer. If you are just uploading files that exist on the local fs,
fastPut is much faster and you don't need to read the local file into a
stream or buffer e.g. fastPut('c:\\path\\to\\local\\file', '/path/to/remote/file');

-- 
Tim Cross

**Comment by coded-monkey** [comment]
It's kind of weird that the api thinks that /INBOX/FTP_debug.txt is a directory is it not?

Just to be sure FTP_debug.txt is a directory in the remote server, I tried calling the apis for some random file and it still thinks it is a directory:

```
2020-03-30 14:18:00.194 INFO  exists for /INBOX: "d" 
2020-03-30 14:18:00.409 INFO  exists for /INBOX/Some_random_file_123456.txt: "d" 
2020-03-30 14:18:00.620 INFO  stat for /INBOX: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 14:18:00.834 INFO  stat for /INBOX/Some_random_file_123456.txt: {"mode":16576,"size":4096,"accessTime":1585497600000,"modifyTime":1585497600000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 14:18:01.051 INFO  cwd: "/" 
```

I tried connecting to a remote server where I can upload files successfully and I get the expected behavior:

```
2020-03-30 14:25:27.774 INFO  exists for /TEST/BNP/BNP_IN: "d" 
2020-03-30 14:25:27.836 INFO  exists for /TEST/BNP/BNP_IN/Some_random_file_123456.txt: false 
2020-03-30 14:25:27.896 INFO  stat for /TEST/BNP/BNP_IN: {"mode":16832,"uid":0,"gid":0,"size":4096,"accessTime":1585540867000,"modifyTime":1585540867000,"isDirectory":true,"isFile":false,"isBlockDevice":false,"isCharacterDevice":false,"isSymbolicLink":false,"isFIFO":false,"isSocket":false} 
2020-03-30 14:25:27.957 ERROR _stat: No such file: /TEST/BNP/BNP_IN/Some_random_file_123456.txt
{"code":"ENOENT","custom":true}

```

**Comment by theophilusx** [comment]
It does seem unusual, but not knowing anything about your remote server,
it is difficult to say. I would try logging in with a low level ftp
client (not a GUI tool) like openssh sftp or lftp. Many of the GUI tools
try to be 'helpful' and can cover up some unusual situations while the
bare bones CLI tools tend to reveal. I would then (while still
connected with the CLI tool, try doing an exists and stat on some files
and examine the remote file system with the CLI tool to see what (if
anything) has changed.

The other thing you can try is using just SSH2 (the module
ssh2-sftp-client uses) and try doing a stat and put using that API. If
it still doesn't work, then the problem could be with SSH2. There are
some examples of using SSH2 in the 'tools' directory of the repository. 

You can also try turning on the debug settings that are in v5.1.2. It
will generate a lot of output, but might provide some more information
about the remote SFTP server. There are a lot of different servers out
there and some quite unusual configurations. While I cannot rule out a
bug in ssh2-sftp-client, I can't do anything unless I can reproduce the
remote environment to try and track down any issue. At this point, there
isn't enough detail to do this. There is some info in the README on
using the debug option. Turning on the debuging might give a clue - it
is possible that ssh2-sftp-client is interpreting the information
returned from the server incorrectly i.e. seeing files as directories
when they are actually files. However, this would mean that the remote
server is returning something 'unusual' in the stat call. Debug might
show this.

As it stands, the information returned by the remote server for a stat()
call indicates the target is a directory. I have no idea why this would
be the case if the server is returning valid information. All I can
guess is that whatever the server is returning is either incorrect or
non-standard.

**Comment by coded-monkey** [comment]
Thanks for your reply. I will try out your suggestions.

One thing I noticed from the stat command, if I send it to the remote server I am having issues with, I do not get the uid and gid parameters from the object returned. Is this normal?

**Comment by theophilusx** [comment]
No, I don't think that is normal. I'll try and write a simple script
that just uses ssh2 to do a stat call and you can run that to see what
the 'raw' data is from the server. Will do that tomorrow.

**Comment by theophilusx** [comment]
OK, I have added the script tools/lowlevel-stat.js to the repository.
This script just uses ssh2/ssh2-streams to do a stat() call on the
remote server and then just dumps the result via console.dir().

The script uses the dotenv package, so to use it, create a .env file
with the login creds in it (see test-env-template in root of repo for
example). Then you can just call the script as

node ./lowlevel-stat.js /path/to/remote/object

Would be interesting to see the output from

node ./lowlevel-stat.js /INBOX

and

node ./lowlevel-stat.js /INBOX/FTP_debug.txt


Examples

Run against a file

╭─tim@tim-desktop ~/git/ssh2-sftp-client/tools  ‹master*› 
╰─➤  node ./lowlevel-stat.js ./test-file1.txt
Running stat on ./test-file1.txt
./test-file1.txt raw stat result
Stats {
  mode: 33204,
  permissions: 33204,
  uid: 30488351,
  gid: 30488351,
  size: 6973257,
  atime: 1576290266,
  mtime: 1576290011
}
╭─tim@tim-desktop ~/git/ssh2-sftp-client/tools  ‹master*› 
╰─➤  

Run against a directory

─tim@tim-desktop ~/git/ssh2-sftp-client/tools  ‹master*› 
╰─➤  node ./lowlevel-stat.js ./testServer    
Running stat on ./testServer
./testServer raw stat result
Stats {
  mode: 16893,
  permissions: 16893,
  uid: 30488351,
  gid: 30488351,
  size: 10,
  atime: 1585721441,
  mtime: 1585721587
}
╭─tim@tim-desktop ~/git/ssh2-sftp-client/tools  ‹master*› 
╰─➤

**Comment by coded-monkey** [comment]
Ok. I will give it a try.

Thanks!

**Comment by theophilusx** [comment]
Any update/progress on this issue?

**Comment by coded-monkey** [comment]
Hi,

Sorry for not updating. No progress yet. I've been in touch with the people who own the remote server I was having problems with. They modified their configuration and as of now, I am able to use the put command without any errors. 

So it looks like the issue is somewhat dependent on the configuration of the remote server. 

They are not done with their configuration so I am unsure if this problem will rear its head once more... But right now I cannot make any progress with investigating this issue.

**Comment by theophilusx** [comment]
OK, thanks for the update.

If it does turn out to be something related to the remote server
configuration, it would be great to get details i.e. server software,
platform, version and what had to be changed. I could at least then add
that to the README in case others encounter a similar issue.
