### ISSUE TITLE
ERROR: ERR_GENERIC_CLIENT - This service allows sftp connections only

### ISSUE THREAD

**Issue by kaaljabr** [theophilusx/ssh2-sftp-client#230]
I don't know what needs to be done here!!
```
sftp.connect({
  host: 'host',
  port: '22',
  username: 'username',
  password: 'pass',
  debug: myDebug,
})
```
I am getting the following error.
```
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
CLIENT[sftp]: Exhausted all connection attempts. Giving up
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
Error: connect: All configured authentication methods failed after 2 attempts
    at Object.formatError (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Client.connectErrorListener (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2-sftp-client/src/index.js:98:21)
    at Object.onceWrapper (events.js:422:26)
    at Client.emit (events.js:315:20)
    at doNextAuth (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:415:12)
    at tryNextAuth (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:597:5)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2-streams/lib/ssh.js:3682:10)
    at SSH2Stream._transform (/Users/XXXX/dev/workspaces/proc-order-sync/node_modules/ssh2-streams/lib/ssh.js:701:13) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
```
It looks like authentication is failing, although I can successfully connect with the same information using CyberDuck a MAC OS app.

**Comment by theophilusx** [comment]
Most likely cause is the remote server is not using one of the default
algorithms used by SSH2 and SSH2-streams library. (default and
supported algorithms depends on node version). Have a look at the ssh2
documentation - under the connect client method there are details about
the 'algorithms' object and the properties it has. You will also need to
check the ssh2-streams documentation, which lists the valid key exchange
and cipher algorithms.

The easiest way I know of to work out which ones you need is to first
connect using something like ssh CLI and turn on debugging so that you
get details of which key exchange and cipher the connection is using.
Then map those values to the corresponding values from the ssh-streams
documentation and add that information to the algorithms object, which
you pass in as options to connect.

I've not run into this issue myself, but others have and this is how
they resolved it. You may find some examples in the closed issues (I
should try and dig one up and add to the readme as an example!).

**Comment by kaaljabr** [comment]
@theophilusx Thanks for your quick reply.
I tried to SSH from a terminal, I got a message saying:
```
$ ssh xxxx@hostaddress
> This service allows sftp connections only.
```
when I did:
```
$ sftp xxxx@hostaddress
```
it worked!

**Comment by kaaljabr** [comment]
This is the debug information I got about the algorithms my SFTP server is using:

```
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-128-etm@openssh.com compression: none
```

So I sent this in the connect options:
```
const algorithms = {
   kex: ['curve25519-sha256@libssh.org'],
   cipher: ['aes128-ctr'],
   serverHostKey: ['ssh-ed25519'],
}
```
I could not find the hmac key. But this failed.

Do you think it is because `umac-128-etm@openssh.com` is not supported by SSH2?

**Comment by kaaljabr** [comment]
More logs from Nodejs app on debug mode:
```
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.4'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:628,padLen:6,remainLen:624
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
DEBUG: KEX algorithm: curve25519-sha256@libssh.org
DEBUG: (local) Host key formats: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
DEBUG: (remote) Host key formats: ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256
DEBUG: Host key format: ssh-ed25519
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:188,padLen:8,remainLen:184
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:1132,padLen:10,remainLen:1120
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_BANNER
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:76,padLen:10,remainLen:64
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:76,padLen:10,remainLen:64
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
CLIENT[sftp]: Connection attempt 1 failed. Trying again.
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
DEBUG: Client: Trying 10.17.112.30 on port 22 ...
DEBUG: Client: Connected
DEBUG: Parser: IN_INIT
DEBUG: Parser: IN_GREETING
DEBUG: Parser: IN_HEADER
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_7.4'
DEBUG: Outgoing: Writing KEXINIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:628,padLen:6,remainLen:624
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
DEBUG: Comparing KEXINITs ...
DEBUG: (local) KEX algorithms: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
DEBUG: (remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
DEBUG: KEX algorithm: curve25519-sha256@libssh.org
DEBUG: (local) Host key formats: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
DEBUG: (remote) Host key formats: ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256
DEBUG: Host key format: ssh-ed25519
DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Client->Server ciphers: aes256-ctr,aes192-ctr,aes128-ctr
DEBUG: Client->Server Cipher: aes128-ctr
DEBUG: (local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
DEBUG: (remote) Server->Client ciphers: aes256-ctr,aes192-ctr,aes128-ctr
DEBUG: Server->Client Cipher: aes128-ctr
DEBUG: (local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Client->Server HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
DEBUG: Client->Server HMAC algorithm: hmac-sha2-256
DEBUG: (local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG: (remote) Server->Client HMAC algorithms: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
DEBUG: Server->Client HMAC algorithm: hmac-sha2-256
DEBUG: (local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Client->Server compression algorithms: none,zlib@openssh.com
DEBUG: Client->Server compression algorithm: none
DEBUG: (local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
DEBUG: (remote) Server->Client compression algorithms: none,zlib@openssh.com
DEBUG: Server->Client compression algorithm: none
DEBUG: Outgoing: Writing KEXECDH_INIT
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:188,padLen:8,remainLen:184
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXECDH_REPLY
DEBUG: Checking host key format
DEBUG: Checking signature format
DEBUG: Verifying host fingerprint
DEBUG: Host accepted by default (no verification)
DEBUG: Verifying signature
DEBUG: Outgoing: Writing NEWKEYS
DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:28,padLen:10,remainLen:16
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: SERVICE_ACCEPT
DEBUG: Outgoing: Writing USERAUTH_REQUEST (none)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:1132,padLen:10,remainLen:1120
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_BANNER
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:76,padLen:10,remainLen:64
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: none auth failed
DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:76,padLen:10,remainLen:64
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:32
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
DEBUG: Client: password auth failed
CLIENT[sftp]: Exhausted all connection attempts. Giving up
DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)
Error: connect: All configured authentication methods failed after 2 attempts
    at Object.formatError (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Client.connectErrorListener (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2-sftp-client/src/index.js:98:21)
    at Object.onceWrapper (events.js:422:26)
    at Client.emit (events.js:315:20)
    at doNextAuth (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:415:12)
    at tryNextAuth (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2/lib/client.js:597:5)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2-streams/lib/ssh.js:3682:10)
    at SSH2Stream._transform (/Users/xxxx/dev/workspaces/proc-order-sync/node_modules/ssh2-streams/lib/ssh.js:701:13) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
} catch error
```

**Comment by theophilusx** [comment]
That debug log indicates password authentication failed. Are you using
passwords or ssh keys for authentication? What version of node and what
platform?

**Comment by kaaljabr** [comment]
I'm using pain password the same password that work when I used sftp from terminl. I tried multiple versions of Node 13 &14 on MAC OS

**Comment by theophilusx** [comment]
My suggestion would be to write a very simple script using just ssh2 and
see if you can get that to authenticate. If it still fails, we know the
issue is with the ssh2 module and you will need to log an issue with
that project. If it works, then the issue is with ssh2-sftp-client and
I'll look at it further. However, as ssh2-sftp-client really just wraps
ssh2 with a promise based API, I suspect if there is an issue, it is
with ssh2. There are some scripts in the 'tools' directory of the
ssh2-sftp-client github repo which show how to write a simple script
based on just ssh2. You can probably use/adapt one one them.

**Comment by kaaljabr** [comment]
@theophilusx thanks for your support.
I have tried SSH2 and that failed too. So I created a ticket there:
https://github.com/mscdex/ssh2/issues/890

You're free to close the ticket if you want.

**Comment by kaaljabr** [comment]
I got it fixed by doing the following:
```
tryKeyboard: true
```
and
```
client.on('keyboard-interactive', (name, instructions, instructionsLang, prompts, finish) => {
  console.log('name %s, instructions %s, instructionsLang %s, prompts', name, instructions, instructionsLang, prompts);
  finish([config.password]);
});
```

**Comment by theophilusx** [comment]
kaaljabr <notifications@github.com> writes:

> I got it fixed by doing the following:
> ```
> tryKeyboard: true
> ```
> and
> ```
> client.on('keyboard-interactive', (name, instructions, instructionsLang, prompts, finish) => {
>   console.log('name %s, instructions %s, instructionsLang %s, prompts', name, instructions, instructionsLang, prompts);
>   finish([config.password]);
> });
> ```

Hmm, that is rather odd. It will be interesting to see what the ssh2
author responds with. Basically, you have to fake keyboard input to get
authentication to work - not seen that before.


-- 
Tim Cross

**Comment by kaaljabr** [comment]
@theophilusx Author of ssh2 just closed the ticket when I said it worked following this way.
So do you think this way is like a workaround which is not really the right way to do it?

**Comment by theophilusx** [comment]
Well, all I can say is I've never needed to do that and all the ftp
servers I've communicated with work fine. It could be that the remote
server is configured to only allow authentication from the keyboard
(which would be unusual). It certainly isn't a 'normal' setup, but if it
works....

-- 
Tim Cross
