### ISSUE TITLE
when i use uploadDir . this ussue appear.

### ISSUE THREAD

**Issue by chinarui-na** [theophilusx/ssh2-sftp-client#239]
{ Error: uploadDir: e.isDirectory is not a function
      at formatError (/Users/chinarui/Documents/workspace/Node/electron/chinarui-admin/node_modules/ssh2-sftp-client/src/utils.js:62:18)
      at Object.handleError (/Users/chinarui/Documents/workspace/Node/electron/chinarui-admin/node_modules/ssh2-sftp-client/src/utils.js:89:13)
      at SftpClient.uploadDir (/Users/chinarui/Documents/workspace/Node/electron/chinarui-admin/node_modules/ssh2-sftp-client/src/index.js:1177:20)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7) code: 'ERR_GENERIC_CLIENT', custom: true }

my code is :

async function main() {
	const client = new Client("icons");
	const src = '/Users/chinarui/Downloads/icons';
	const dst = '/home/icons';

	try {
		await client.connect(config);
		client.on('upload', info => {
			console.log(`Listener: Uploaded ${info.source}`);
		});
		let rslt = await client.uploadDir(src, dst);
		console.log(rslt)
		return rslt;
	} finally {
		client.end();
	}
}

main()
	.then(msg => {
		console.log(msg);
	})
	.catch(err => {
		console.log(err)
	});

**Comment by chinarui-na** [comment]
the code in src/index.js 
     let dirEntries = fs.readdirSync(localInfo.path, {
        encoding: 'utf8',
        withFileTypes: true
      });
the dirEntries is [ '.DS_Store', 'favicon.ico', 'index.html' ] 
but when i test such as:
var fs = require('fs')
var localInfo = '/Users/chinarui/Downloads/icons'
let dirEntries = fs.readdirSync(localInfo, {
        encoding: 'utf8',
        withFileTypes: true
      })
;
console.log(dirEntries)

the dieEntries is :
[
  Dirent { name: '.DS_Store', [Symbol(type)]: 1 },
  Dirent { name: 'favicon.ico', [Symbol(type)]: 1 },
  Dirent { name: 'index.html', [Symbol(type)]: 1 }
]

**Comment by chinarui-na** [comment]
i use it with electron
