### ISSUE TITLE
Facing error when uploading multiple files to sftp

### ISSUE THREAD

**Issue by eyad-kobatte** [theophilusx/ssh2-sftp-client#255]
Hello, Our use case is to currently send a bunch of files (~200) to an SFTP server through AWS Lambda. We have set up the lambda with only a limit of 5 concurrent executions, so the max number of SFTP connections will not go above 5. We are also reusing the same connection once a lambda gets invoked again, so the connections are not being closed and then reopened for each file.

The problem we are seeing is this error comes up when we try to transfer a lot of files (~200 files).

```
{
    "errorType": "Error",
    "errorMessage": "put: Failure <FILE_NAME>",
    "code": "ERR_GENERIC_CLIENT",
    "custom": true,
    "stack": [
        "Error: put: Failure <FILE_NAME>",
        "    at Object.formatError (/var/task/node_modules/ssh2-sftp-client/src/utils.js:62:18)",
        "    at WriteStream.<anonymous> (/var/task/node_modules/ssh2-sftp-client/src/index.js:677:24)",
        "    at Object.onceWrapper (events.js:422:26)",
        "    at WriteStream.emit (events.js:315:20)",
        "    at WriteStream.EventEmitter.emit (domain.js:482:12)",
        "    at errorOrDestroy (internal/streams/destroy.js:108:12)",
        "    at onwriteError (_stream_writable.js:424:5)",
        "    at onwrite (_stream_writable.js:445:5)",
        "    at /var/task/node_modules/ssh2-streams/lib/sftp.js:3057:14",
        "    at cb (/var/task/node_modules/ssh2-streams/lib/sftp.js:969:15)"
    ]
}
```

We have looked into relevant issues and seen that opening alot of connections would cause issues. We are also ignoring the issue that happens on sftp.end when we get ECONNRESET

This is how we reuse connections

At the beginning of the function

```
const sftp = new Client();
let isSftpConnected = false;
```

When we to connect to SFTP

```
if (!isSftpConnected) {
    await sftp.connect({
        username: process.env.SFTP_USER_NAME,
        host: process.env.SFTP_HOST,
        privateKey,
        port: 22,
        debug: (msg) => {
            logger.info({ debug: msg });
        },
    });
    isSftpConnected = true;
}
```

And this is how we transfer files

```
const directoryExist = await sftp.exists(directory);
try {
    if (directoryExist === false) {
        await sftp.mkdir(directory, true);
    }
} catch (error) {
    if (error.code !== 4) {
        /*
            Error code 4 is when 2 instances try to create the same directory at the same time. This is a
            possibility in our lambda and can be ignored as we can assume that the directory was already
            created by another instance
        */
        throw error;
    }
}
await sftp.put(body, key);
```

We have try catches everywhere in our actual code so all errors will be caught but try catch has been removed in these snippets.

We have also enabled debugger and these are the logs we get right before the error log

```
{"debug":"DEBUG: Parser: Verifying MAC","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_WINDOW_ADJUST (0, 129330)","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETBEFORE (expecting 16)","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKET","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: Decrypting","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: pktLen:44,padLen:6,remainLen:32","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATA","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: Decrypting","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: HMAC size:32","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATAVERIFY","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: Verifying MAC","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)","LEVEL":"INFO"}
{"debug":"DEBUG[SFTP]: Parser: Response: STATUS","LEVEL":"INFO"}
{"debug":"DEBUG[SFTP]: Outgoing: Writing CLOSE","LEVEL":"INFO"}
{"debug":"DEBUG: Outgoing: Writing CHANNEL_DATA (0)","LEVEL":"INFO"}
{"debug":"CLIENT[sftp]: Removing listener from error","LEVEL":"INFO"}
{"debug":"CLIENT[sftp]: Removing listener from close","LEVEL":"INFO"}
{"debug":"CLIENT[sftp]: Removing listener from error","LEVEL":"INFO"}
{"debug":"CLIENT[sftp]: Removing listener from close","LEVEL":"INFO"}
{"debug":"DEBUG: Parser: IN_PACKETBEFORE (expecting 16)","LEVEL":"INFO"}
```

The SFTP server is on unix

Node version: 12

Package version: 5.2.2

Any help on this would be appreciated. Thank You :)

**Comment by eyad-kobatte** [comment]
Hi again. Thanks for all the information you provided. We did manage to fix this issue in the end. It looked like the issue was mainly due to the concurrency.

We cannot move from lambda as that's a requirement for us in the end. So we modified our workflow to look like this. We only trigger the lambda once per batch of our files (once per ~200 files). The lambda then downloads all files from S3 (all files are pretty small in size) and then uses `sftp.uploadDir` to upload the whole directory into SFTP. Since it uses `fastPut`, and only uploads one at a time, it has no issues

I think the main issue was the fact that we do `sftp.put` without a lot of time in between the operations and the SFTP server rejected all these operations happening together.
