### ISSUE TITLE
end() method

### ISSUE THREAD

**Issue by PingRui** [theophilusx/ssh2-sftp-client#333]
Error: end: Remote host has reset the connection: read ECONNRESET
    at fmtError (C:\Users\Administrator\Desktop\wechat\node_modules\ssh2-sftp-client\src\utils.js:53:18)
    at Client.fn (C:\Users\Administrator\Desktop\wechat\node_modules\ssh2-sftp-client\src\utils.js:73:16)
    at Client.emit (events.js:215:7)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\wechat\node_modules\ssh2\lib\client.js:724:12)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  custom: true
}
C:\Users\Administrator\Desktop\wechat\node_modules\ssh2\lib\protocol\crypto\poly1305.js:20
function J(a){if(b.onAbort)b.onAbort(a);L(a);O=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");r(a);throw a;}var V="data:application/octet-stream;base64,",W="data:application/octet-stream;base64,AGFzbQEAAAABIAZgAX8Bf2ADf39/AGABfwBgAABgAAF/YAZ/f39/f38AAgcBAWEBYQAAAwsKAAEDAQAAAgQFAgQFAXABAQEFBwEBgAKAgAIGCQF/AUGAjMACCwclCQFiAgABYwADAWQACQFlAAgBZgAHAWcABgFoAAUBaQAKAWoBAAqGTQpPAQJ/QYAIKAIAIgEgAEEDakF8cSICaiEAAkAgAkEAIAAgAU0bDQAgAD8AQRB0SwRAIAAQAEUNAQtBgAggADYCACABDwtBhAhBMDYCAEF/C4wFAg5+Cn8gACgCJCEUIAAoAiAhFSAAKAIcIREgACgCGCESIAAoAhQhEyACQRBPBEAgAC0ATEVBGHQhFyAAKAIEIhZBBWytIQ8gACgCCCIYQQVsrSENIAAoAgwiGUEFbK0hCyAAKAIQIhpBBWytIQkgADUCACEIIBqtIRAgGa0hDiAYrSEMIBatIQoDQCASIAEtAAMiEiABLQAEQQh0ciABLQAFQRB0ciABLQAGIhZBGHRyQQJ2Qf///x9xaq0iAyAOfiABLwAAIAEtAAJBEHRyIBNqIBJBGHRBgICAGHFqrSIEIBB+fCARIAEtAAdBCHQgFnIgAS0ACEEQdHIgAS0ACSIRQRh0ckEEdkH///8fcWqtIgUgDH58IAEtAApBCHQgEXIgAS0AC0EQdHIgAS0

RuntimeError: abort(Error: end: Remote host has reset the connection: read ECONNRESET). Build with -s ASSERTIONS=1 for more info.
    at process.J (C:\Users\Administrator\Desktop\wechat\node_modules\ssh2\lib\protocol\crypto\poly1305.js:20:53)
    at process.emit (events.js:210:5)
    at processEmit [as emit] (C:\Users\Administrator\Desktop\wechat\node_modules\signal-exit\index.js:161:32)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by theophilusx** [comment]
This is a normal error telling you that your remote sftp server has
reset the connection. You need to investigate why the remote sftp server
is resetting the connection.

**Comment by theophilusx** [comment]
Is this issue now able to be closed?

**Comment by PingRui** [comment]
> 这个问题现在可以关闭了吗？

Problem solved. Thanks for your help!
