### ISSUE TITLE
Uncatchable exception "Error: end: No SFTP connection available at haveConnection" when there is an auth failure connecting to sftp service

### ISSUE THREAD

**Issue by dylanatimdex** [theophilusx/ssh2-sftp-client#420]
Occurs in 9.0.1 and 9.0.0

```
CLIENT[sftp]: connect: Debugging turned on
console.pub.js:42CLIENT[sftp]: ssh2-sftp-client Version: 9.0.0 { "node": "16.15.1", "v8": "9.4.146.24-node.21", "uv": "1.43.0", "zlib": "1.2.11", "brotli": "1.0.9", "ares": "1.18.1", "modules": "93", "nghttp2": "1.47.0", "napi": "8", "llhttp": "6.0.4", "openssl": "1.1.1o+quic", "cldr": "40.0", "icu": "70.1", "tz": "2021a3", "unicode": "14.0", "ngtcp2": "0.1.0-DEV", "nghttp3": "0.1.0-DEV" }
console.pub.js:42CLIENT[sftp]: connect: Connect attempt 1
console.pub.js:42Custom crypto binding not available
console.pub.js:42Local ident: 'SSH-2.0-ssh2js1.11.0'
console.pub.js:42Client: Trying <HOST NAME> on port 22 ...
console.pub.js:42Socket connected
console.pub.js:42Remote ident: 'SSH-2.0-AzureSSH_1.0.0'
console.pub.js:42Outbound: Sending KEXINIT
console.pub.js:42Inbound: Handshake in progress
console.pub.js:42Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
console.pub.js:42Handshake: (remote) KEX method: ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,ext-info-s
console.pub.js:42Handshake: KEX algorithm: ecdh-sha2-nistp256
console.pub.js:42Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
console.pub.js:42Handshake: (remote) Host key format: rsa-sha2-256,rsa-sha2-512,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384
console.pub.js:42Handshake: Host key format: ecdsa-sha2-nistp256
console.pub.js:42Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
console.pub.js:42Handshake: (remote) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr
console.pub.js:42Handshake: C->S Cipher: aes128-gcm@openssh.com
console.pub.js:42Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
console.pub.js:42Handshake: (remote) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr
console.pub.js:42Handshake: S->C cipher: aes128-gcm@openssh.com
console.pub.js:42Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
console.pub.js:42Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
console.pub.js:42Handshake: C->S MAC: <implicit>
console.pub.js:42Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
console.pub.js:42Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
console.pub.js:42Handshake: S->C MAC: <implicit>
console.pub.js:42Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
console.pub.js:42Handshake: (remote) C->S compression: none
console.pub.js:42Handshake: C->S compression: none
console.pub.js:42Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
console.pub.js:42Handshake: (remote) S->C compression: none
console.pub.js:42Handshake: S->C compression: none
console.pub.js:42Outbound: Sending KEXECDH_INIT
console.pub.js:42Received DH Reply
console.pub.js:42Host accepted by default (no verification)
console.pub.js:42Host accepted (verified)
console.pub.js:42Outbound: Sending NEWKEYS
console.pub.js:42Inbound: NEWKEYS
console.pub.js:42Verifying signature ...
console.pub.js:42Verified signature
console.pub.js:42Handshake completed
console.pub.js:42Outbound: Sending SERVICE_REQUEST (ssh-userauth)
console.pub.js:42Inbound: Received SERVICE_ACCEPT (ssh-userauth)
console.pub.js:42Outbound: Sending USERAUTH_REQUEST (none)
console.pub.js:42Inbound: Received USERAUTH_FAILURE (publickey,password)
console.pub.js:42Client: none auth failed
console.pub.js:42Outbound: Sending USERAUTH_REQUEST (password)
console.pub.js:42Inbound: Received USERAUTH_FAILURE (publickey,password)
console.pub.js:42Client: password auth failed
console.pub.js:42CLIENT[sftp]: Global: Ignoring handled error: All configured authentication methods failed
console.pub.js:42Outbound: Sending DISCONNECT (11)
console.pub.js:42CLIENT[sftp]: getConnection: getConnection: All configured authentication methods failed (ERR_BAD_AUTH)
**console.pub.js:42LanguageWorkerConsoleLog[error] Worker 0f300a06-d91b-4a0c-9350-3c31c3e4b722 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: end: No SFTP connection available at haveConnection (<projectroot>\node_modules\ssh2-sftp-client\src\utils.js:252:20) at <projectroot>\node_modules\ssh2-sftp-client\src\index.js:1532:11 at new Promise (<anonymous>) at SftpClient.end (<projectroot>\node_modules\ssh2-sftp-client\src\index.js:1523:12) at SftpClient.connect (<projectroot>\node_modules\ssh2-sftp-client\src\index.js:261:12) at processTicksAndRejections (node:internal/process/task_queues:96:5)**
```

I suspect that this was fixed in commit [4b0fafa61f8357f56fc2e00a1257161b24871632](https://github.com/theophilusx/ssh2-sftp-client/commit/4b0fafa61f8357f56fc2e00a1257161b24871632)

**Comment by theophilusx** [comment]
Yes, that has already been changed in master branch of repo. Please try with that code. I will be releasing it soon as 9.0.2

**Comment by theophilusx** [comment]
Have pushed 9.0.2 which fixes this issue. Closing.

**Comment by theophilusx** [comment]
Yes, I believe that has been fixed in current master. Please see if you
can reproduce using HEAD from the master branch.
