### ISSUE TITLE
Signature verification failed: Error: error:03000098:digital envelope routines::invalid digest

### ISSUE THREAD

**Issue by sushantKulkarniUnivar** [theophilusx/ssh2-sftp-client#455]
Hello, 
I am getting this error while trying to connect to sftp folders from AWS ECR instance. 
The connection works fine in the local machine. AWS doesn't seem to be the problem as we have other applications running on Java and python that are able to connect on the same network. 
Any more info on debugging this issue is appreciated 

The current systems that I am running on 

Node Version: 16.17.1
ssh2-sftp-client version: 9.0.4

The code : 

```
 async connect()
    {
        if (this.client) {
            return;
        }
        this.client = new SFTPClient();
        await this.client.connect(<any>{
            host: process.env.SFTP_HOST,
            port: process.env.SFTP_PORT,
            username: process.env.SFTP_USER,
            password: process.env.SFTP_PASS,
            debug: console.log
        });
    }

```
The logs :

```
2022-12-19T09:10:17.245-06:00	CLIENT[sftp]: connect: Debugging turned on

2022-12-19T09:10:17.245-06:00	CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4 {

2022-12-19T09:10:17.245-06:00	"node": "16.17.1",

2022-12-19T09:10:17.245-06:00	"v8": "9.4.146.26-node.22",

2022-12-19T09:10:17.245-06:00	"uv": "1.43.0",

2022-12-19T09:10:17.245-06:00	"zlib": "1.2.11",

2022-12-19T09:10:17.245-06:00	"brotli": "1.0.9",

2022-12-19T09:10:17.245-06:00	"ares": "1.18.1",

2022-12-19T09:10:17.245-06:00	"modules": "93",

2022-12-19T09:10:17.245-06:00	"nghttp2": "1.47.0",

2022-12-19T09:10:17.245-06:00	"napi": "8",

2022-12-19T09:10:17.245-06:00	"llhttp": "6.0.9",

2022-12-19T09:10:17.245-06:00	"openssl": "3.0.1",

2022-12-19T09:10:17.245-06:00	"cldr": "41.0",

2022-12-19T09:10:17.245-06:00	"icu": "71.1",

2022-12-19T09:10:17.245-06:00	"tz": "2022a",

2022-12-19T09:10:17.245-06:00	"unicode": "14.0"

2022-12-19T09:10:17.245-06:00	}

2022-12-19T09:10:17.246-06:00	CLIENT[sftp]: connect: Connect attempt 1

2022-12-19T09:10:17.248-06:00	Custom crypto binding not available

2022-12-19T09:10:17.249-06:00	Local ident: 'SSH-2.0-ssh2js1.11.0'

2022-12-19T09:10:17.250-06:00	Client: Trying  <ip address> on port 22 ...

2022-12-19T09:10:17.303-06:00	Socket connected

2022-12-19T09:10:17.492-06:00	Remote ident: 'SSH-2.0-7.9.0.0_openssh GlobalSCAPE'

2022-12-19T09:10:17.493-06:00	Outbound: Sending KEXINIT

2022-12-19T09:10:17.509-06:00	Inbound: Handshake in progress

2022-12-19T09:10:17.510-06:00	Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512

2022-12-19T09:10:17.510-06:00	Handshake: (remote) KEX method: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

2022-12-19T09:10:17.510-06:00	Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256

2022-12-19T09:10:17.510-06:00	Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa

2022-12-19T09:10:17.510-06:00	Handshake: (remote) Host key format: ssh-rsa

2022-12-19T09:10:17.510-06:00	Handshake: Host key format: ssh-rsa

2022-12-19T09:10:17.510-06:00	Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com

2022-12-19T09:10:17.510-06:00	Handshake: (remote) C->S cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr

2022-12-19T09:10:17.510-06:00	Handshake: C->S Cipher: aes128-ctr

2022-12-19T09:10:17.510-06:00	Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com

2022-12-19T09:10:17.510-06:00	Handshake: (remote) S->C cipher: aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr

2022-12-19T09:10:17.510-06:00	Handshake: S->C cipher: aes128-ctr

2022-12-19T09:10:17.510-06:00	Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1

2022-12-19T09:10:17.510-06:00	Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1

2022-12-19T09:10:17.510-06:00	Handshake: C->S MAC: hmac-sha2-256

2022-12-19T09:10:17.510-06:00	Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1

2022-12-19T09:10:17.510-06:00	Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha1

2022-12-19T09:10:17.510-06:00	Handshake: S->C MAC: hmac-sha2-256

2022-12-19T09:10:17.510-06:00	Handshake: (local) C->S compression: none,zlib@openssh.com,zlib

2022-12-19T09:10:17.510-06:00	Handshake: (remote) C->S compression: zlib,none

2022-12-19T09:10:17.510-06:00	Handshake: C->S compression: none

2022-12-19T09:10:17.511-06:00	Handshake: (local) S->C compression: none,zlib@openssh.com,zlib

2022-12-19T09:10:17.511-06:00	Handshake: (remote) S->C compression: zlib,none

2022-12-19T09:10:17.511-06:00	Handshake: S->C compression: none

2022-12-19T09:10:17.511-06:00	Outbound: Sending KEXDH_GEX_REQUEST

2022-12-19T09:10:17.613-06:00	Received DH GEX Group

2022-12-19T09:10:17.756-06:00	Outbound: Sending KEXDH_GEX_INIT

2022-12-19T09:10:17.878-06:00	Received DH GEX Reply

2022-12-19T09:10:17.879-06:00	Received DH Reply

2022-12-19T09:10:17.879-06:00	Host accepted by default (no verification)

2022-12-19T09:10:17.879-06:00	Host accepted (verified)

2022-12-19T09:10:17.879-06:00	Outbound: Sending NEWKEYS

2022-12-19T09:10:17.880-06:00	Inbound: NEWKEYS

2022-12-19T09:10:18.014-06:00	Verifying signature ...

2022-12-19T09:10:18.017-06:00	Signature verification failed: Error: error:03000098:digital envelope routines::invalid digest

2022-12-19T09:10:18.017-06:00	at verifyOneShot (node:internal/crypto/sig:288:39)

2022-12-19T09:10:18.017-06:00	at OpenSSH_Public.verify (/usr/src/app/node_modules/ssh2/lib/protocol/keyParser.js:408:18)

2022-12-19T09:10:18.017-06:00	at DHGroupExchange.finish (/usr/src/app/node_modules/ssh2/lib/protocol/kex.js:669:40)

2022-12-19T09:10:18.017-06:00	at DHGroupExchange.parse (/usr/src/app/node_modules/ssh2/lib/protocol/kex.js:1216:25)

2022-12-19T09:10:18.017-06:00	at Protocol.onKEXPayload (/usr/src/app/node_modules/ssh2/lib/protocol/kex.js:1767:20)

2022-12-19T09:10:18.017-06:00	at NullDecipher.decrypt (/usr/src/app/node_modules/ssh2/lib/protocol/crypto.js:612:26)

2022-12-19T09:10:18.017-06:00	at Protocol.parsePacket [as _parse] (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)

2022-12-19T09:10:18.017-06:00	at Protocol.parse (/usr/src/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)

2022-12-19T09:10:18.017-06:00	at Socket.<anonymous> (/usr/src/app/node_modules/ssh2/lib/client.js:713:21)

2022-12-19T09:10:18.017-06:00	at Socket.emit (node:events:513:28)

2022-12-19T09:10:18.017-06:00	at Socket.emit (node:domain:489:12)

2022-12-19T09:10:18.017-06:00	at addChunk (node:internal/streams/readable:315:12)

2022-12-19T09:10:18.017-06:00	at readableAddChunk (node:internal/streams/readable:289:9)

2022-12-19T09:10:18.017-06:00	at Socket.Readable.push (node:internal/streams/readable:228:10)

2022-12-19T09:10:18.017-06:00	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

2022-12-19T09:10:18.017-06:00	Outbound: Sending DISCONNECT (3)

2022-12-19T09:10:18.018-06:00	CLIENT[sftp]: connect errorListener - ignoring handled error

2022-12-19T09:10:18.018-06:00	CLIENT[sftp]: Global: Ignoring handled error: Handshake failed: signature verification failed

2022-12-19T09:10:18.035-06:00	Socket ended

2022-12-19T09:10:18.035-06:00	CLIENT[sftp]: connect endListener - ignoring handled error

2022-12-19T09:10:18.035-06:00	CLIENT[sftp]: Global: Ignoring hanlded end event

2022-12-19T09:10:18.035-06:00	Socket closed
```

**Comment by sushantKulkarniUnivar** [comment]
Is this ssh2-sftp-client issue or is it a ssh issue?

**Comment by theophilusx** [comment]
As ssh2-sftp-client is really just a wrapper around ssh2 and doesn't
directly do any of the actual network, encryption or socket handling, my
expectation is that this will be an ssh2 issue. All that
ssh2-sftp-client really does is wrap the ssh2 API in a promise based
API.

Unfortunately, in order to get the ssh2 project to look at this issue,
it will be necessary to create a minimal example, using just ssh2, which
reproduces the issue.

There are some sample ssh2 scripts in the validate directory of the
ssh2-sftp-client repository which may be a good starting basis for a
minimal example which can reproduce the issue your seeing.

Unfortunately, I don't hav time to look at this right now (hopeuflly I
will have time in 2-3 weeks).
