### ISSUE TITLE
 code: 'ERR_GENERIC_CLIENT', only on digital ocean

### ISSUE THREAD

**Issue by HannanSolo** [theophilusx/ssh2-sftp-client#456]
I am getting the infamous ` code: 'ERR_GENERIC_CLIENT',`  but only when running the code from my digital ocean server.

I am connecting and downloading a file, then disconnecting. 

But I get this error in my logs.
```
Error: connect: getConnection: Timed out while waiting for handshake
code: 'ERR_GENERIC_CLIENT',
```
When I run my code locally it works perfectly. Which stumps me as to why it doesn't work on a server. The server I am connecting to does not have IP whitelisting.

Not sure what is causing this issue and any advice solving it would be greatly appreciated.

Here are the logs of the failed connection on digital ocean.
```
 CLIENT[sftp]: connect: Debugging turned on
 CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4  {
  "node": "16.19.0",
  "v8": "9.4.146.26-node.24",
  "uv": "1.43.0",
  "zlib": "1.2.11",
  "brotli": "1.0.9",
  "ares": "1.18.1",
  "modules": "93",
  "nghttp2": "1.47.0",
  "napi": "8",
  "llhttp": "6.0.10",
  "openssl": "1.1.1s+quic",
  "cldr": "41.0",
  "icu": "71.1",
  "tz": "2022f",
  "unicode": "14.0",
  "ngtcp2": "0.8.1",
  "nghttp3": "0.7.0"
 }
 CLIENT[sftp]: connect: Connect attempt 1
 Custom crypto binding available
 Local ident: 'SSH-2.0-ssh2js1.11.0'
 Client: Trying goanywherecltnr.bkiconnect.com on port 22 ...
 CLIENT[sftp]: connect errorListener - ignoring handled error
 CLIENT[sftp]: Global: Ignoring handled error: Timed out while waiting for handshake
 Socket closed
 CLIENT[sftp]: connect closeListener - ignoring handled error
 CLIENT[sftp]: Global: Ignoring handled close event
 CLIENT[sftp]: connect: Connect attempt 2
 Custom crypto binding available
 Local ident: 'SSH-2.0-ssh2js1.11.0'
 Client: Trying goanywherecltnr.bkiconnect.com on port 22 ...
 CLIENT[sftp]: connect errorListener - ignoring handled error
 CLIENT[sftp]: Global: Ignoring handled error: Timed out while waiting for handshake
 CLIENT[sftp]: connect: getConnection: Timed out while waiting for handshake (ERR_GENERIC_CLIENT)
 Error: connect: getConnection: Timed out while waiting for handshake
     at SftpClient.fmtError (/workspace/node_modules/ssh2-sftp-client/src/index.js:111:22)
     at SftpClient.connect (/workspace/node_modules/ssh2-sftp-client/src/index.js:249:37)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async /workspace/.next/server/pages/api/digest/mls.js:119:28
     at async /workspace/node_modules/mela-api/dist/index.js:1:561
     at async Object.apiResolver (/workspace/node_modules/next/dist/server/api-utils/node.js:366:9)
     at async NextNodeServer.runApi (/workspace/node_modules/next/dist/server/next-server.js:481:9)
     at async Object.fn (/workspace/node_modules/next/dist/server/next-server.js:735:37)
     at async Router.execute (/workspace/node_modules/next/dist/server/router.js:247:36)
     at async NextNodeServer.run (/workspace/node_modules/next/dist/server/base-server.js:347:29) {
   code: 'ERR_GENERIC_CLIENT',
   custom: true
 }
 Socket closed
 CLIENT[sftp]: end: Connection closed
 CLIENT[sftp]: end closeListener - ignoring handled error
 CLIENT[sftp]: Global: Ignoring handled close event
```

And here's the successful connection from my machine
```
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: ssh2-sftp-client Version: 9.0.4  {
 "node": "18.10.0",
 "v8": "10.2.154.15-node.12",
 "uv": "1.43.0",
 "zlib": "1.2.11",
 "brotli": "1.0.9",
 "ares": "1.18.1",
 "modules": "108",
 "nghttp2": "1.47.0",
 "napi": "8",
 "llhttp": "6.0.10",
 "openssl": "3.0.5+quic",
 "cldr": "41.0",
 "icu": "71.1",
 "tz": "2022b",
 "unicode": "14.0",
 "ngtcp2": "0.8.1",
 "nghttp3": "0.7.0"
}
CLIENT[sftp]: connect: Connect attempt 1
Custom crypto binding available
Local ident: 'SSH-2.0-ssh2js1.11.0'
Client: Trying goanywherecltnr.bkiconnect.com on port 22 ...
Socket connected
Remote ident: 'SSH-2.0-GoAnywhere7.0.1'
Outbound: Sending KEXINIT
Inbound: Handshake in progress
Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
Handshake: (remote) KEX method: diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,ext-info-s
Handshake: KEX algorithm: ecdh-sha2-nistp256
Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Handshake: (remote) Host key format: rsa-sha2-256,ssh-rsa,rsa-sha2-512,ssh-dss
Handshake: Host key format: rsa-sha2-512
Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) C->S cipher: aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: C->S Cipher: aes256-gcm@openssh.com
Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,chacha20-poly1305@openssh.com,aes256-ctr
Handshake: (remote) S->C cipher: aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
Handshake: S->C cipher: aes256-gcm@openssh.com
Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com
Handshake: C->S MAC: <implicit>
Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
Handshake: S->C MAC: <implicit>
Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
Handshake: (remote) C->S compression: none,zlib
Handshake: C->S compression: none
Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
Handshake: (remote) S->C compression: none,zlib
Handshake: S->C compression: none
Outbound: Sending KEXECDH_INIT
Received DH Reply
Host accepted by default (no verification)
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_BANNER
Inbound: Received USERAUTH_FAILURE (password,publickey,keyboard-interactive)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection ready listener: got connection - promise resolved
Outbound: Sending CHANNEL_OPEN (r:0, session)
Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
```

**Comment by theophilusx** [comment]
The first thing you need to do is ensure that the underlying ssh2 module
used by ssh2-sftp-client is loading the appropriate 
algorithms and ciphers.

Best way to do this is to use openssh CLI with the debugging turned all
the way up and do a connect and file transfer to your digital oceans
sftp server. This will show you what key exchange algorithms and ciphers
are being negotiated. It is possible that it is using either algorithms
or ciphers which are not loaded by default in ssh2. Once you know which
algorithms and ciphers are being used, you can ensure they are loaded by
ssh2 by adding them to the connect properties passed in.

See the ssh2 project documentation for details on how to load or force
specific algorithms/ciphers. Note that the names used by openssh and
ssh2 can be slightly different. The mapping is fairly obvious - just
make sure your using the algorithm and cipher names referred to in the
ssh2 documentation.

If it turns out openssh is using something not supported by ssh2, you
will need to tweak what ssh2 is willing to offer/negotiate and hope one
will work. Essentially, you need to experiment to find the right
:algorithms property value.

**Comment by HannanSolo** [comment]
I have tried every algorithm to no success. After a lot of debugging and a Digital Ocean, it seems SFTP or FTP is not allowed on its App Platform deployments, only its droplets. No way around that.

I appreciate your help and responses, though. :)
