### ISSUE TITLE
"Failed to generate information to decrypt key" using empty password

### ISSUE THREAD

**Issue by QAnders** [theophilusx/ssh2-sftp-client#535]
```json
CLIENT[sftp]: connect: Debugging turned on
CLIENT[sftp]: ssh2-sftp-client Version: 10.0.3  {
 "node": "18.14.2",
 "v8": "10.2.154.26-node.22",
 "uv": "1.44.2",
 "zlib": "1.2.13",
 "brotli": "1.0.9",
 "ares": "1.18.1",
 "modules": "108",
 "nghttp2": "1.51.0",
 "napi": "8",
 "llhttp": "6.0.10",
 "uvwasi": "0.0.14",
 "acorn": "8.8.1",
 "simdutf": "3.1.0",
 "undici": "5.20.0",
 "openssl": "3.0.8+quic",
 "cldr": "42.0",
 "icu": "72.1",
 "tz": "2022g",
 "unicode": "15.0",
 "ngtcp2": "0.8.1",
 "nghttp3": "0.7.0"
}
CLIENT[sftp]: connect: Connect attempt 1
CLIENT[sftp]: getConnection: Cannot parse privateKey: Failed to generate information to decrypt key
CLIENT[sftp]: end: Called when no connection active
CLIENT[sftp]: connect: Cannot parse privateKey: Failed to generate information to decrypt key (ERR_GENERIC_CLIENT)
Catch Error:  Error: connect: Cannot parse privateKey: Failed to generate information to decrypt key
    at SftpClient.fmtError (/home/anders/qvalia-serverless-tasks/node_modules/ssh2-sftp-client/src/index.js:87:22)
    at SftpClient.connect (/home/anders/qvalia-serverless-tasks/node_modules/ssh2-sftp-client/src/index.js:225:37)
    at async sftpToCustomer (/home/anders/qvalia-serverless-tasks/src/functions/sftptocustomer/sftptocustomer.service.js:78:3)
    at async exports.run (/home/anders/qvalia-serverless-tasks/src/functions/sftptocustomer/handler.js:17:17) {
  code: 'ERR_GENERIC_CLIENT',
  custom: true
}
```

We have a setup with a Test (QA) instance and one Production instance. In Production the Private key is using a passphrase, and the code works fine, the SFTP connection and transfer is successful.
However, in Test where the Private key has no passphrase it fails with the above error.

Is it possible to support a Private key that has no passphrase?

Trying to remove the attribute `passphrase`, or setting it to `null` or `undefined` instead throws:
```
Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given
```

**Comment by theophilusx** [comment]
This is something which is handled by the ssh2 library, so nothing I can do directly from the ssh2-sftp-client level. You would need to log an issue with the ssh2 project. 

One thing you probably can do is write a custom auth handler. See the ssh2 documentation regarding this.
