### ISSUE TITLE
NodeJS deprecation warning

### ISSUE THREAD

**Issue by gjstreicher** [theophilusx/ssh2-sftp-client#548]
When using this dependency with NodeJS version `22.5.1` I get the following NodeJS deprecation warning:

```
DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
```

When using the `--trace-deprecation` flag with `node` I get the following trace:
```
(node:116789) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
    at attrsToBytes (PROJECT_PATH/node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:2492:45)
    at SFTP.open (PROJECT_PATH/node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:331:15)
    at WriteStream.open (PROJECT_PATH/node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:3899:13)
    at new WriteStream (PROJECT_PATH/node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:3883:10)
    at SFTP.createWriteStream (PROJECT_PATH/node_modules/.pnpm/ssh2@1.15.0/node_modules/ssh2/lib/protocol/SFTP.js:311:12)
    at PROJECT_PATH/node_modules/.pnpm/ssh2-sftp-client@10.0.3/node_modules/ssh2-sftp-client/src/index.js:714:25
    at new Promise (<anonymous>)
    at SftpClient._put (PROJECT_PATH/node_modules/.pnpm/ssh2-sftp-client@10.0.3/node_modules/ssh2-sftp-client/src/index.js:704:12)
    at SftpClient.put (PROJECT_PATH/node_modules/.pnpm/ssh2-sftp-client@10.0.3/node_modules/ssh2-sftp-client/src/index.js:768:25)
    at file:///PROJECT_PATH/tables/shared/backup-mutable-full.js:56:30
```

**Comment by theophilusx** [comment]
ssh2-sftp-client does not use the util.isDate API. Likely something used
by the ssh2 library. You could log an issue with that project.
