### ISSUE TITLE
使用pnpm安装了ssh2-sftp-client，运行项目时，提示加载cpufeatures.node失败，查看了node_modules，直接没有build文件夹

### ISSUE THREAD

**Issue by luo-hong-kai** [theophilusx/ssh2-sftp-client#549]
```
X [ERROR] Could not resolve "../build/Release/cpufeatures.node"

    ../../node_modules/.pnpm/cpu-features@0.0.10/node_modules/cpu-features/lib/index.js:3:24:
      3 │ const binding = require('../build/Release/cpufeatures.node');
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

D:\develop\projects\hk-mssh\hongkai-node\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
../../node_modules/.pnpm/cpu-features@0.0.10/node_modules/cpu-features/lib/index.js:3:24: ERROR: Could not resolve "../build/Release/cpufeatures.node"
    at failureErrorWithLog (D:\develop\projects\hk-mssh\hongkai-node\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1472:15)
    at D:\develop\projects\hk-mssh\hongkai-node\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:945:25
    at D:\develop\projects\hk-mssh\hongkai-node\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```
上面时项目运行时，提示的错误信息

**Comment by theophilusx** [comment]
This error is from ssh2 and nothing to do with ssh2-sftp-client. You
will need to report this issue to the ssh2 repository.

Note that the error is from an optional ssh2 dependency. It will not
prevent use of ssh2 or ssh2-sftp-client.
